### ISSUE TITLE
Vagrant Manager stuck on refreshing

### ISSUE THREAD

**Issue by xymox12** [lanayotech/vagrant-manager-windows#23]
Hi - just installed the windows version and it is stuck on refreshing. I am running vagrant version 1.8.1
 I thought I would report this as I notice that Mac users are reporting a similiar issue: https://github.com/lanayotech/vagrant-manager/issues/118

Thanks

**Comment by joshuaadickerson** [comment]
Same here. Just started when I ran a Windows 10 update. Though, that also happened to be the time that I upgraded Vagrant to 1.8.1 because the Win 10 update broke everything so I had to uninstall VBox and Vagrant and then reinstall.

**Comment by joshuaadickerson** [comment]
Then it dies...

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Bitmap.GetHicon()
   at Lanayo.Vagrant_Manager.Menu.NativeMenu.UpdateRefreshIcon(Object s, EventArgs args)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Lanayo.VagrantManager
    Assembly Version: 1.0.0.3
    Win32 Version: 1.0.0.3
    CodeBase: file:///C:/Program%20Files%20(x86)/Vagrant%20Manager/Lanayo.VagrantManager.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
SharpSparkle
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Vagrant%20Manager/SharpSparkle.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by raremedia** [comment]
I am also experiencing this issue. 
Windows 10 latest
Vagrant Manager 1.0.0.3
Vagrant 1.8.1
VirtualBox 5.0.14

**Comment by magnetik** [comment]
Same here:
Windows 7 pro,
Vagrant manager 1.0.0.3
Vagrant 1.8.1
Virtualbox 5.0.12

**Comment by joshuaadickerson** [comment]
Cool. I didn't realize Vagrant Manager for Windows is no longer actively developed.

**Comment by crayfishuk** [comment]
Yep and here
Windows 10 v 1511
Vagrant 1.8.1
Virtualbox 5.0.16
VagrantManager 1.0.0.3

**Comment by amitailanciano** [comment]
looks like the icon needs to be destroyed manually when a new one is generated or else it leaks, I'll put out a fix for that as well as some of the other issues as soon as I have some time to work on it

**Comment by sambolek** [comment]
Hope this will be solved soon, as I'd really like to try this. Would make live easier for some of my non-technical colleagues.

**Comment by amitailanciano** [comment]
This should be resolved in 1.0.0.4

**Comment by xKairu** [comment]
The 1.0.0.4 release still says 1.0.0.3 in About and still infinitely refreshes, is there a mixup in the release?

**Comment by amitailanciano** [comment]
@xKairu should be resolved in 1.0.0.5 -- the constant refresh was a separate issue

**Comment by noahziheng** [comment]
Windows 10 latest
Vagrant Manager 1.0.0.5
Vagrant 1.8.5
VirtualBox 5.1.2
The same problem is came...

**Comment by morokin** [comment]
Same bug here:

Windows 10 latest
Vagrant Manager 1.0.0.5
Vagrant 1.8.5
VirtualBox 5.1.4
Hope it will be solved soon.

**Comment by MarkSummers** [comment]
@amitailanciano this is not resolved.  Same issue with Vagrant 1.8.5 and latest Windows 10.

**Comment by narration-sd** [comment]
Yes, unfortunately this came back, I am pretty sure with Windows 10 1607 upgrade.

You can Up a machine successfully, but the status is never indicated, so you can't see that it's up, nor halt it etc..

All very latest Vagrant, Virtualbox, Windows Updates, etc. as of yesterday.

It's a nice thing to have, Vagrant Manager, missed for moment,, but appreciate your work  ;)

**Comment by MarkSummers** [comment]
I think I found the cause of the Windows issue:

https://github.com/lanayotech/vagrant-manager-windows/issues/28

**Comment by narration-sd** [comment]
Great work, Mark, and sounds right what you found. 

Hope we can see a result to try out before long - maybe from pull request, as that goes well between languages?

Cheers,
Clive

**Comment by amitailanciano** [comment]
Release [1.0.0.6](https://github.com/lanayotech/vagrant-manager-windows/releases/tag/1.0.0.6) should resolve this issue, thanks again for your contribution @MarkSummers

**Comment by narration-sd** [comment]
It seems to work very well again, many thanks, Amitai. 

Also great to find the new actions - will be useful...

Best,
Clive

**Comment by ryanaltvater** [comment]
@amitailanciano I'm experiencing this same issue on Windows 10 with Vagrant 2.1.1 and Vagrant Manager 1.0.0.6 installed.

I also tried running VM as administrator and it had no affect.

**Comment by chpock** [comment]
@ryanaltvater 1.0.0.7 version from this repository https://github.com/deveres/vagrant-manager-windows works

**Comment by ryanaltvater** [comment]
@chpock That worked. Not sure how I overlooked the 1.0.0.7 release for 1.0.0.6. "Check for updates" didn't seem to pick it up either. Thank you!
